### ISSUE TITLE
Bug: DAO may not fully load on creation

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#664] opened 2022-11-14 19:05 UTC
### Overview

When Creating a Gnosis Safe DAO, the data may not be available yet in the API. We should probably setup some sort of polling to occur for a set amount of time to keep trying, before prompting the user to refresh maybe?

### Steps to reproduce

Create Safe (Multisig) DAO -> Deploy DAO.

It should redirect you probably but may get stuck in a loading state.

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Chrome (or Chromium based)

### Operating System

Mac

### web3 wallet

MetaMask

**Comment by herbig** [comment] 2022-12-02 21:58
closing as a duplicate of https://github.com/decent-dao/fractal-interface/issues/632

**Closed by herbig** 2022-12-02 21:58 UTC
Labels: bug
