### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#983] opened 2023-02-17 02:07 UTC
### Overview

In Proposal Details in the right box.
The lines within the process bar are misaligned

### Steps to reproduce

- DAO Type: Token Voting DAO
- Parent DAO
- 1/1 tokens
- Voted on a createSubDAO proposal
- 100% approval

### Screenshots / Video

![image](https://user-images.githubusercontent.com/38386583/219531019-e432ebaf-805f-4032-90a4-dc5ef89e8deb.png)

### Version

Prod (app.fractalframework.xyz/)

### Browser

Chrome (or Chromium based)

### Operating System

None

### web3 wallet

None

**Comment by herbig** [comment] 2023-02-18 01:58
Duplicate of https://github.com/decent-dao/fractal-interface/issues/979 and fixed in https://github.com/decent-dao/fractal-interface/pull/984

**Closed by herbig** 2023-02-18 01:58 UTC
Labels: bug
