### ISSUE TITLE
Bug: NumberInputs

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/fractal-interface#763] opened 2022-12-12 17:43 UTC
So it looks like the NumberInputs from 'Chakra` have set javascript number limit on thier inputs. so if any number say 10000000000000000 is entered into the input, onBlur this number is update to the max number allowed by Javascript.

This can be fixed for now but update all inputs to a normal `Input` component and using the `onKeyDown` methods to block any unwanted characters

**Comment by herbig** [comment] 2022-12-13 19:52
Duplicate of https://github.com/decent-dao/fractal-interface/issues/754

**Closed by herbig** 2022-12-13 19:52 UTC
Labels: bug
